name: Laer CI/CD
on: [push]
jobs:
  build:
    name: Build and Test Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      - name: Setup Maven Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Wait Maven Build and Test
        run: mvn --batch-mode --update-snapshots verify
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Wait Render Deploy
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          service-id: ${{ secrets.SERVICE_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retries: 20
          wait: 16000
          sleep: 30000
